### ISSUE TITLE
is there a test case?

### ISSUE THREAD

**Issue by jiaoyilun** [dog-gateway/jamod-rtu-over-tcp#2]
help,   how to use it ,is there a  test case for rtu over tcp/ip?

**Comment by dbonino** [comment]
Dear @jiaoyilun,
thank you for contacting us. This is a fork of the jamod library (http://jamod.sourceforge.net) and you can find the library documentation at their official site. This fork only adds support to RTU over TCP tunneled connections, which is not natively available in Jamod. The way of using the library is exactly the same as for the original; We just added a RTUTCPMasterConnection which implements the MasterConnection interface for the RTU over TCP case. The usage pattern is almost equal to the one of a normal TCPMasterConnection.
Unfortunately we do not have detailed documentation, but you can have a look at how it is used in our Modbus Driver for Dog, at https://github.com/dog-gateway/modbus-drivers. In particular in the it.polito.elite.dog.drivers.modbus.network package.

**Comment by jiaoyilun** [comment]
@dbonino all right, thank you , i will have a loot at it
